### ISSUE TITLE
DiscordStreamer is making new empty folders

### ISSUE THREAD

**Issue by GameplaysRFun** [TeamCernodile/DiscordStreamer#12]
I've tried to delete these, but they just re-appear after a few songs or two. Take a look.
![selection_005](https://cloud.githubusercontent.com/assets/9896328/21546547/670e2922-ce1a-11e6-99da-2097d4a11b3f.png)
![selection_006](https://cloud.githubusercontent.com/assets/9896328/21546571/97cc502a-ce1a-11e6-90ea-09d68034a08c.png)

**Comment by cernodile** [comment]
Identifying, seems fine on my workspace

**Comment by GameplaysRFun** [comment]
Alright, I believe it may have something to do with main.js

**Comment by cernodile** [comment]
No, it's possibly how the ytdl saves file, might be a typo or something. I remember this occuring yesterday, but I reckon fixing it locally.

**Comment by GameplaysRFun** [comment]
Okay

**Comment by cernodile** [comment]
Resolved in upcoming build.
