### ISSUE TITLE
New option to automatically restart bot if crashed

### ISSUE THREAD

**Issue by GameplaysRFun** [TeamCernodile/DiscordStreamer#15]
Could add a new option to automatically restart the bot if it crashes (it's easier and more convenient for those who are not 24/7 on their hosts). It could also be disabled for development bots so owners can take crash logs.

**Comment by DoctorDarkMagic** [comment]
You are full of ideas.

**Comment by GameplaysRFun** [comment]
Haha, more to come ;3

**Comment by cernodile** [comment]
We've tried to make auto-reconnect system, we'll have to see how it goes first. Should be resolved in next build.
