### ISSUE TITLE
Add ->help to direct users to GitHub

### ISSUE THREAD

**Issue by GameplaysRFun** [TeamCernodile/DiscordStreamer#16]
->help should direct users to [https://github.com/TeamCernodile/DiscordStreamer](https://github.com/TeamCernodile/DiscordStreamer) where readme.md is located at so users can view the commands and usage.

**Comment by DoctorDarkMagic** [comment]
I like this idea.

**Comment by BrennanFlory** [comment]
it shouldnt redirect but give a link to it. As the help command should be a in chat response of something along the lines of 
`if help [comand] -> send description for that command`
`if help -> send list of commands and a link to the https://github.com/TeamCernodile/DiscordStreamer/wiki`

**Comment by BrennanFlory** [comment]
ontp of this i feel the wiki needs to be documented better with clear install instructions for windows, linix(ubuntu) on a pc, linix(ubuntu) on a server, raspbian, and osx
when you document something document it so that the user who knows nothing about programing can run it

**Comment by GameplaysRFun** [comment]
@BrennanFlory Coming Soon, give it some time, it just started yesterday, and also I meant _direct_ users to readme.md not redirect, my bad haha

**Comment by BrennanFlory** [comment]
i know its coming soon i just wanted to vocalize the fact that the documentation needs work

**Comment by GameplaysRFun** [comment]
Alright. I will work on it in a few hours.

**Comment by BrennanFlory** [comment]
im willing to help out if yall want it

**Comment by cernodile** [comment]
Planned update, coming in upcoming update. Not much left to do.
