### ISSUE TITLE
Volume Equalizer

### ISSUE THREAD

**Issue by GameplaysRFun** [TeamCernodile/DiscordStreamer#17]
I know it may be a bit of work, but there should be a way to set the volume of certain songs (some are too loud, some are too quiet). Maybe in main.js or worker.js?

**Comment by BrennanFlory** [comment]
there is a way im not to sure on how to do it with js

**Comment by cernodile** [comment]
Giving equalizer to the hands of normal people would be dangerous, also using inlineVolume will make your CPU usage go VERY high, so rejected.
