### ISSUE TITLE
Icon not appearing in ->queue

### ISSUE THREAD

**Issue by GameplaysRFun** [TeamCernodile/DiscordStreamer#18]
At certain times, ->queue does not load the icon (no timeout errors in log):

![image](https://cloud.githubusercontent.com/assets/9896328/21559049/a58b5318-ce7f-11e6-86ce-af663d9e7156.png)

**Comment by cernodile** [comment]
That is the nature of how embeds work, someetimes they fail, nothing we can do about it, really.
