### ISSUE TITLE
Add insufficient permissions message

### ISSUE THREAD

**Issue by GameplaysRFun** [TeamCernodile/DiscordStreamer#19]
The bot should return an insufficient permissions message and the required rank for that command (e.g. a user executes ->add, the bot should return `Insufficient Permissions! Required: DJ+`, a DJ executes ->eval, the bot should return `Insufficient Permissions! Required: Masteruser`)

**Comment by BrennanFlory** [comment]
+1

**Comment by cernodile** [comment]
This should be easy to do, coming in next build.
