### ISSUE TITLE
Halp

### ISSUE THREAD

**Issue by Cat-who-loves-bots** [TeamCernodile/DiscordStreamer#2]
Halp my eyes are burning from that code

**Comment by Nenkai** [comment]
I dare you to do better.

**Comment by DoctorDarkMagic** [comment]
Really?

**Comment by cernodile** [comment]
We're having a major rewrite coming soon, and we do not intend to rush it. It'll take some time but it's worth the wait! Will be more stable, and more readable than before.
Closing as it doesn't have any useful information in it.
