### ISSUE TITLE
Create scrollable playlist (->queue 2 etc.)

### ISSUE THREAD

**Issue by GameplaysRFun** [TeamCernodile/DiscordStreamer#20]
This is just a suggestion, it's not really needed but it's useful in finding where the song you want is ;3

**Comment by cernodile** [comment]
Well, it's deffinetly not impossible, we'll look into it.

**Comment by BrennanFlory** [comment]
i web ui would make this easier

**Comment by GameplaysRFun** [comment]
@BrennanFlory It depends because even if Web UI would allow non-ranked users to utilize the service, it doesn't mean they will go and look at it.

**Comment by cernodile** [comment]
Web UI is temporarily discontinued, and it shouldn't be hard to make the pagination, I'll try to do it for next build 👍
