### ISSUE TITLE
Add page number in ->queue

### ISSUE THREAD

**Issue by GameplaysRFun** [TeamCernodile/DiscordStreamer#22]
Add the page number in ->queue to keep track of which page you're currently on, it could be either `Page 1/3` or `Page 1` only, maybe make it configurable too in main.js, but that's unnecessary too :P

**Comment by jaacks** [comment]
Considering that it's on an infinite loop, adding pages would go on forever. Seems unnecessary.

**Comment by cernodile** [comment]
Well, we would have no way of checking (or no "pretty" way) the pagination, but it's possible. It'd be dirty, though.
