### ISSUE TITLE
Add a YouTube Playlist

### ISSUE THREAD

**Issue by BrennanFlory** [TeamCernodile/DiscordStreamer#23]
It would be nice to be able to do ->add [youtube playlist] to add multiple songs at once

**Comment by cernodile** [comment]
Would require a YouTube API key, and if you're hosting a larger scale of bots, you'd get restricted from API pretty easily. So this feature is currently between yes and no.

**Comment by BrennanFlory** [comment]
maybe a way to import a list of youtube links in a txt file. with a sleep or wait after every x songs as this souldnt need to be done often

**Comment by cernodile** [comment]
I'm doing research on how to avoid the API key thing, I know it should be possible, but not sure still. I'll update you when I find it.

**Comment by jaacks** [comment]
Potentially looping all songs and adding them could work?

**Comment by BrennanFlory** [comment]
i could show you how i do it in python if you want

**Comment by GameplaysRFun** [comment]
As @BrennanFlory said, maybe put it in a txt file, and then add a new command to make the bot read the txt files (of course, you need to specify the format of links). When the bot receives the command, it will read the txt file and import the songs. Once imported, it will tell the user it is safe to delete the txt file, even though a txt file really doesn't make a difference in playlists since you have to add them manually... I'm looking at this: https://sourceforge.net/projects/youtubeexport/

**Comment by BrennanFlory** [comment]
you could just use ytdl for it

**Comment by cernodile** [comment]
How would I be getting the .txt of the IDs in first place, hm?

**Comment by BrennanFlory** [comment]
have it within the command like !import [name of file].txt

**Comment by jaacks** [comment]
@BrennanFlory That would make sense but you'd have to compile a ton of YouTube links into one .txt.

**Comment by BrennanFlory** [comment]
not if you already have a program to do that

**Comment by jaacks** [comment]
Do you know any programs that do that task?

**Comment by BrennanFlory** [comment]
yeah i have a few

```python
import youtube_dl

ytdl_format_options = {
    'format': 'bestaudio/best',
    'extractaudio': True,
    'audioformat': "mp3",
    'outtmpl': '%(id)s',
    'noplaylist': True,
    'nocheckcertificate': True,
    'ignoreerrors': True,
    'quiet': True,
    'no_warnings': True
}

ytdl = youtube_dl.YoutubeDL(ytdl_format_options)

playlist = "https://www.youtube.com/playlist?list=PL5TK9CoRomoVDxgaYJG_DExAKsjIYgiwk"

with open(Classical.txt', 'w+') as f:
    for e in ytdl.extract_info(playlist, download=False, process=False)['entries']:
        if e:
            f.write('https://www.youtube.com/watch?v={}'.format(e['url']))
```

**Comment by BrennanFlory** [comment]
but thats in python

**Comment by BrennanFlory** [comment]
and you just replace that playlist link whit the one you want

**Comment by jaacks** [comment]
Bud, this is JavaScript.

**Comment by BrennanFlory** [comment]
i know but that can still work to get the txt files from a playlist on the user side i havent worked a lot with js so i dont feel comfortable making something to be added to the bot
if only it was a c lib

**Comment by jaacks** [comment]
Well, it's not. Too bad man.

**Comment by DoctorDarkMagic** [comment]
I have done adding youtube playlists with my bot. But as @cernodile has said, the API Key. And most people don't even have Google accounts.

**Comment by GameplaysRFun** [comment]
The API key can cause some issues so definitely not using that :/

**Comment by DoctorDarkMagic** [comment]
Exactly, so really this issue should be closed.

**Comment by GameplaysRFun** [comment]
@BrennanFlory  Reopen the issue if you do find a solution in JS.

**Comment by DoctorDarkMagic** [comment]
*Doubt it*
