### ISSUE TITLE
Command to end process

### ISSUE THREAD

**Issue by GameplaysRFun** [TeamCernodile/DiscordStreamer#26]
There should be a command similar to `->eval bot.disconnect();` but instead of only disconnecting and leaving the terminal to run the empty process, the command should be able to end the process (right now after executing `->eval bot.disconnect();`, I have to do Ctrl + C to end the process).

**Comment by jaacks** [comment]
Do you mean a total shutdown, or a restart?
If it is a total shutdown, that could be added.

**Comment by jaacks** [comment]
Done.
