### ISSUE TITLE
Permission check on initialization

### ISSUE THREAD

**Issue by GameplaysRFun** [TeamCernodile/DiscordStreamer#27]
The bot should check for permissions before initializing the stream, i.e. it tries sending text to the channel to verify it has the appropriate permissions to run. (it has returned errors before when I didn't give it permission to send text, so why not use that as an advantage?)

**Comment by cernodile** [comment]
It's possible, by checking your channel permissions, shouldn't be hard.

**Comment by GameplaysRFun** [comment]
To add on, the bot should not proceed to stream music, instead tell you what permissions you need to give it, and for what channel it's missing.

**Comment by jaacks** [comment]
We could also add a trigger so if the `vc` ID is not set it shuts down.
