### ISSUE TITLE
Console log should show ID of song currently streaming

### ISSUE THREAD

**Issue by GameplaysRFun** [TeamCernodile/DiscordStreamer#30]
Instead of:
`DiscordStreamer: Streaming epic sax gandalf 1 hour HD`
It could show:
`DiscordStreamer: Streaming epic sax gandalf 1 hour HD [6ktnrKG8uq4]`

**Comment by jaacks** [comment]
By ID, do you mean "YouTube `watch` ID"?

**Comment by GameplaysRFun** [comment]
@jaacks Yep.
