### ISSUE TITLE
Removal of songs using URL

### ISSUE THREAD

**Issue by GameplaysRFun** [TeamCernodile/DiscordStreamer#31]
`->remove` should be able to resolve URLs and remove the prefix of www.youtube.com/watch?v= instead of only being able to read the ID.

**Comment by cernodile** [comment]
That would be quite difficult, because we'd have to 100% parse the youtube links, more processing again, making it bit more unstable in cost of usability.

**Comment by GameplaysRFun** [comment]
Got it.
