### ISSUE TITLE
Set default bitrate to 64kbps

### ISSUE THREAD

**Issue by GameplaysRFun** [TeamCernodile/DiscordStreamer#34]
When ffmpeg is closed, the error message appears:
```
Uh oh! I've encountered an error, please send this to my owner!

Error: Command failed: [libopus @ 000000000205aa00] No bit rate set. Defaulting to 96000 bps.
```
It was my mistake by closing FFMPEG, but the thing is, most voice channels default to 64000 bps. Shouldn't it default to 64000 bps too?

**Comment by cernodile** [comment]
*sigh* I don't know where to start with this...

You do know if we made it 64kbps, it'd sound like absolute bullcrap... By default most API libraries go from 96kbps-128kbps (Even if you set slider to 64kbps, bot accounts CAN ignore it).
What you are requesting is actually API library side issue, which we cannot solve for you, and I doubt the API library owner would either.

This is most likely related to a 0-byte file, or unfinished downloading file, when you end your bot abruptly while it's downloaded.
