### ISSUE TITLE
Use same ffmpeg prompt

### ISSUE THREAD

**Issue by GameplaysRFun** [TeamCernodile/DiscordStreamer#35]
In Windows, DiscordStreamer re-opens a new command prompt after every song to run ffmpeg.exe. It should run in the same prompt like RethinkDB instead of creating a new prompt every time, anything you guys can do about this?

**Comment by Nenkai** [comment]
Don't think that is possible, as it is a ffmpeg/ytdl-core thing

**Comment by GameplaysRFun** [comment]
I was thinking maybe it could execute `ffmpeg` with the /k variable, but I'm still researching.

**Comment by cernodile** [comment]
That's API library side issue, which we are not fixing.
