### ISSUE TITLE
supportDevs spam reduction

### ISSUE THREAD

**Issue by GameplaysRFun** [TeamCernodile/DiscordStreamer#38]
I was thinking, on an interval of broadcastTime, the bot checks for the supportDevs broadcast (if there are any new user messages that came after the broadcast) and it will not broadcast a new message unless the last message sent on the channel was a user message. (Basically reducing the spam)

**Comment by DoctorDarkMagic** [comment]
Quit with the labels 😂  Someone else should do that if they agree :P

**Comment by GameplaysRFun** [comment]
Nuuuuu @DoctorDarkMagic I had and still have one job and it's labelling issues! I love labels <3 now shoo shoo lemme do my job :P
