### ISSUE TITLE
Dealing with errors and unstable gateway

### ISSUE THREAD

**Issue by cernodile** [TeamCernodile/DiscordStreamer#39]
Currently DiscordStreamer has major issues with error handling and gateway being extremely unstable. Investigation is required, and proper measures set, as gateway drops and errors occur randomly. Any assistance given would be appreciated a lot.

**Comment by itslukej** [comment]
#32

**Comment by DoctorDarkMagic** [comment]
Disconnecting from the channel after a while is happening to a lot of bots including my own. I think this is an issue with Discord.

**Comment by GameplaysRFun** [comment]
Doesn't seem fixable from the bot itself :/

**Comment by DoctorDarkMagic** [comment]
Discords fault I guess.
