### ISSUE TITLE
Restart function

### ISSUE THREAD

**Issue by GameplaysRFun** [TeamCernodile/DiscordStreamer#41]
Add ->restart to make the bot destroy it's own instance and start up again... the start up again part sounds a little impossible though... but if this was possible it would fix a lot of issues without `pm2 restart`.

**Comment by DoctorDarkMagic** [comment]
That may interfere, we can do something like a `child_process.exec('pm2 restart <thisid>')`.

**Comment by cernodile** [comment]
@DoctorDarkMagic How would we get the pm2 process ID first, though?

**Comment by DoctorDarkMagic** [comment]
I have no idea, it could be a setting maybe?

**Comment by cernodile** [comment]
...which would mean hardcoding each process to work like that

**Comment by DoctorDarkMagic** [comment]
Yeah, stuff the pm2 idea. But yet still, the bots getting destroyed might not work, I have had problems with it.

**Comment by cernodile** [comment]
We'd have to run DiscordStreamer as child process then, and restart if certain conditions are met.

**Comment by DoctorDarkMagic** [comment]
Mhm.

**Comment by GameplaysRFun** [comment]
@cernodile @DoctorDarkMagic Bump.

**Comment by DoctorDarkMagic** [comment]
I don't think theres much need.

**Comment by itslukej** [comment]
I dont think you are much need

**Comment by DoctorDarkMagic** [comment]
rip
