### ISSUE TITLE
->skip Skips twice

### ISSUE THREAD

**Issue by LimMingXuan** [TeamCernodile/DiscordStreamer#5]
I typed ->skip once and it skipped two songs

**Comment by LimMingXuan** [comment]
Sorry, here's what happened:
`DiscordStreamer: Streaming Cash Cash & Digital Farm Animals - Millionaire (ft. Nelly) | Alan Walker Remix
DiscordStreamer: Gameplays R Fun#5015 executed <skip>
DiscordStreamer: Streaming DEAF KEV - Invincible [NCS Release]
DiscordStreamer: Gameplays R Fun#5015 executed <skip> <-- did not execute
DiscordStreamer: Streaming Chime & Adam Tell - Whole [NCS Release]
(node:21718) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: 404 NOT FOUND on DELETE /channels/262804998008602624/messages/263492000324517890
DiscordStreamer: Gameplays R Fun#5015 executed <queue>
DiscordStreamer: Gameplays R Fun#5015 executed <queue> <-- did not execute
DiscordStreamer: Streaming Light Years Away - Melrose At Midnight [NCS Release]
DiscordStreamer: Gameplays R Fun#5015 executed <queue>
DiscordStreamer: Gameplays R Fun#5015 executed <queue> <-- did not execute
DiscordStreamer: Gameplays R Fun#5015 executed <queue>
DiscordStreamer: Gameplays R Fun#5015 executed <queue> <-- did not execute
`

**Comment by cernodile** [comment]
It seems as you were attempting to stream a unavailable song for your region, please find out the video ID by evaluating `.map(u => {if (u.name === "Light Years Away - Melrose At Midnight [NCS Release]") {all.rawData.r.table('playlist').get(u).delete().run(all.rawData.conn, () => {})}});` using `eval` command!
We'll be sure to fix invalid videos in the future, thanks for using DiscordStreamer!

**Comment by cernodile** [comment]
Alright, we've indentified this issue, seems like we went to a slippery slope and need to perform a surgery on this release! Patch incoming soon!

**Comment by LimMingXuan** [comment]
Awesome!
